Add an unsupported caveat for hpc
SUSE/suse-migration-services pull request #242
Opened 2022-04-18 15:11 UTC by KeithMnemonic

This PR adds a note about migrations for SLE 12 HPC not being supported.

2022-04-19 16:56 UTC, guangyee commented
Looks good to me!

2022-04-19 18:48 UTC, guangyee approved these changes

2022-04-20 10:24 UTC, jesusbv approved these changes

2022-04-20 13:12 UTC, rtamalin approved these changes
LGTM

2022-04-20 13:51 UTC, rjschwei requested changes

2022-04-20 13:51 UTC, rjschwei commented on doc/adoc/user_guide.adoc
> +  corresponding SLE 12 HPC product, a migration path from SLE 12 HPC to SLE 15 HPC
s/SLE 12 HPC/SLE 12/

mentioning what looks like a product name after we state it does not exist is confusing.

2022-04-25 11:43 UTC, rjschwei approved these changes

2022-04-25 11:43 UTC, merged