DRAFT: Add pre-checks as a systemd process
SUSE/suse-migration-services pull request #245
Opened 2022-04-26 21:16 UTC by KeithMnemonic

This PR completes the updated implementation of suse-migration-pre-checks.  A new suse-migration-run-pre-checks-service has been added that will be started right after the instance is rebooted to the migration image and the filesystem is mounted at /system-root. 

One PR #244 is merged, this PR will be updated to include the `--fix` option as the default behavior when the suse-migration-run-pre-checks-service is started.  A new option config has been added to allow this to be turned off. In that mode, the pre-checks are still run but without the `--fix` fix option.

2022-04-27 11:59 UTC, rtamalin commented
Looks good.

2022-05-04 17:46 UTC, rjschwei requested changes

2022-05-04 17:46 UTC, rjschwei commented on package/suse-migration-services-spec-template
> +Conflicts:        suse-migration-pre-checks
The pre-checks and the migration services both need to be installed in the Live ISO system that does the migration, they cannot conflict.

2022-05-25 22:10 UTC, KeithMnemonic commented
closing this in favor of https://github.com/SUSE/suse-migration-services/pull/247  . There were some rebase issues so I applied the change to a fresh pull of master

2022-05-25 22:10 UTC, closed without merging